Add debug step for Docker Hub username secret
Add a step to debug visibility of Docker Hub username secret.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,6 +16,16 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
+      - name: Debug secrets visibility
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "Username secret is missing"
+            exit 1
+          else
+            echo "Username secret found"
+          fi
+
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
